[package]
authors = ["Sebastian Wicki <gandro@gmx.net>"]
name = "postgres-logical-replication"
version = "0.1.0"

[dependencies]
bytes = "0.4.5"
fallible-iterator = "0.1.3"
postgres-protocol = "0.3.1"
postgres-shared = "0.4.0"
